### PR TITLE
Update Lex design

### PR DESCRIPTION
**Pull request by Nooba**
- [x] Update Splashscreen animation (waiting for final version with shadow)
- [x] Update AppIcon
- [x] Update Loader animation
- - [x] It’s prepared to receive a lottie animation. Uses the Splash lottie as a placeholder for now
- - [x] Switch it to the final loader lottie animation
- [x] Update primary color

https://github.com/user-attachments/assets/707b9c6f-74a6-4907-ae9d-caaf1e857d9b

https://github.com/user-attachments/assets/bdce36f3-c817-47b9-9368-e0c3ec9ba283

Bonus:
Also fixed SNL target missing loader (it was using a single image but missing the asset. Switched it back to multiple images)

### CODE REVIEW

**Review by haaakon — APPROVED** [review]

**Comment by haaakon** [comment]
What do you need to complete the todo list?

**Comment by Nooba** [comment]
@haaakon The last lottie animation (the loader) from Andreas whenever he has time.

**Comment by haaakon** [comment]
Did you add the other fix they wanted too? Or will that be a separate PR?

**Comment by Nooba** [comment]
@haaakon Just added it as a separate PR.

**Pull request merged**
